name: 🚀 Publish to NPM
on:
  release:
    types: [created]
jobs:
  release:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout
        uses: actions/checkout@v2
      - name: 🟢 node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: 🧪 Run tests
        run: npm test
      - name: 🚀 Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"
